"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.nearbyRoomsQuerySchema = exports.createRoomSchema = exports.loginAuthSchema = exports.upgradeAuthSchema = exports.anonymousAuthSchema = exports.selectWaitlistSchema = exports.insertWaitlistSchema = exports.authAuditLogs = exports.participants = exports.messages = exports.chatRooms = exports.users = exports.waitlist = void 0;
var schema_1 = require("./schema");
Object.defineProperty(exports, "waitlist", { enumerable: true, get: function () { return schema_1.waitlist; } });
Object.defineProperty(exports, "users", { enumerable: true, get: function () { return schema_1.users; } });
Object.defineProperty(exports, "chatRooms", { enumerable: true, get: function () { return schema_1.chatRooms; } });
Object.defineProperty(exports, "messages", { enumerable: true, get: function () { return schema_1.messages; } });
Object.defineProperty(exports, "participants", { enumerable: true, get: function () { return schema_1.participants; } });
Object.defineProperty(exports, "authAuditLogs", { enumerable: true, get: function () { return schema_1.authAuditLogs; } });
Object.defineProperty(exports, "insertWaitlistSchema", { enumerable: true, get: function () { return schema_1.insertWaitlistSchema; } });
Object.defineProperty(exports, "selectWaitlistSchema", { enumerable: true, get: function () { return schema_1.selectWaitlistSchema; } });
Object.defineProperty(exports, "anonymousAuthSchema", { enumerable: true, get: function () { return schema_1.anonymousAuthSchema; } });
Object.defineProperty(exports, "upgradeAuthSchema", { enumerable: true, get: function () { return schema_1.upgradeAuthSchema; } });
Object.defineProperty(exports, "loginAuthSchema", { enumerable: true, get: function () { return schema_1.loginAuthSchema; } });
Object.defineProperty(exports, "createRoomSchema", { enumerable: true, get: function () { return schema_1.createRoomSchema; } });
Object.defineProperty(exports, "nearbyRoomsQuerySchema", { enumerable: true, get: function () { return schema_1.nearbyRoomsQuerySchema; } });
